"use client";
import { motion, useReducedMotion } from "framer-motion";
import { Activity, RotateCcw } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";

const models=["Llama-3-70B","Mistral-Large","Custom-RAG-Pipeline"];
const spring={type:"spring" as const,stiffness:200,damping:25};
export function InfrastructureDashboard(){
 const [model,setModel]=useState(models[2]),[tick,setTick]=useState(0),[resetting,setResetting]=useState(false),[active,setActive]=useState(true);const root=useRef<HTMLElement>(null),reduced=useReducedMotion();
 useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setActive(entry.isIntersecting),{rootMargin:"150px"});if(root.current)observer.observe(root.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!active||reduced)return;const timer=setInterval(()=>setTick(v=>v+1),1500);return()=>clearInterval(timer)},[active,reduced]);
 const data=useMemo(()=>Array.from({length:22},(_,i)=>42+Math.sin((i+tick)*.75)*9+Math.cos((i+tick)*.31)*5),[tick]);
 const points=data.map((value,i)=>`${i/21*100},${54-(value-28)*1.35}`).join(" ");
 const flush=()=>{setResetting(true);setTimeout(()=>{setTick(0);setResetting(false)},650)};
 const logs=["Embedding node loaded","Vector space synchronized","Reranker health check passed","KV cache allocation stable"];
 return <section ref={root} id="infrastructure" className="relative z-10 scroll-mt-20 border-t border-white/[.07] px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-7xl"><header className="mb-12"><p className="font-mono text-[10px] tracking-[.22em] text-cyan-300">05 / INFRASTRUCTURE OBSERVABILITY</p><h2 className="mt-3 text-4xl font-bold tracking-[-.045em] sm:text-6xl">Model execution, made observable.</h2><p className="mt-5 max-w-2xl text-slate-400">Browser-generated observability data demonstrating inference monitoring interface design.</p><span className="mt-4 inline-block rounded-full border border-violet-400/20 px-3 py-1 font-mono text-[9px] text-violet-300">SIMULATED RUNTIME TELEMETRY</span></header>
 <div className="grid gap-5 lg:grid-cols-2">
  <article className="glass-card min-h-[350px] p-6"><div className="flex justify-between font-mono text-[9px]"><span className="text-cyan-300">NODE_01 / RUNTIME</span><span className="text-[#5ee6c4]">● ACTIVE</span></div><div className="mt-6 rounded-xl border border-white/[.06] bg-black/50 p-4 font-mono text-[10px] leading-7">{logs.map((x,i)=><motion.p key={x} animate={{opacity:resetting?0:.35+i*.18,x:resetting?-8:0}} transition={spring} className="text-slate-400">[{String(tick+i).padStart(4,"0")}] {x}...</motion.p>)}</div><div className="mt-6 flex gap-2 overflow-x-auto">{models.map(x=><button key={x} onClick={()=>setModel(x)} className={`whitespace-nowrap rounded-lg border px-3 py-2 font-mono text-[9px] ${model===x?"border-violet-400/40 bg-violet-400/10 text-violet-200":"border-white/[.07] text-slate-600"}`}>{x}</button>)}</div></article>
  <article className="glass-card min-h-[350px] p-6"><div className="flex justify-between font-mono text-[9px]"><span className="text-cyan-300">NODE_02 / TOKEN_THROUGHPUT</span><b className="text-white">{resetting?0:Math.round(data.at(-1)||0)} TPS</b></div><svg viewBox="0 0 100 60" className="mt-8 h-56 w-full" role="img" aria-label="Simulated tokens per second sparkline"><defs><linearGradient id="spark" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#35d9ff" stopOpacity=".24"/><stop offset="1" stopColor="#35d9ff" stopOpacity="0"/></linearGradient></defs>{[15,30,45].map(y=><line key={y} x1="0" x2="100" y1={y} y2={y} stroke="#202941" strokeWidth=".25"/>)}<polygon points={`0,60 ${resetting?"0,54 100,54":points} 100,60`} fill="url(#spark)"/><polyline points={resetting?"0,54 100,54":points} fill="none" stroke="#35d9ff" strokeWidth=".65" vectorEffect="non-scaling-stroke"/></svg><p className="font-mono text-[9px] text-slate-600">MODEL: {model} · POLL: 1.5s</p></article>
  <article className="glass-card min-h-[330px] p-6"><div className="flex justify-between font-mono text-[9px]"><span className="text-cyan-300">NODE_03 / LATENCY</span><span className="text-slate-600">SIMULATED</span></div><div className="mt-8 space-y-7">{[["Prompt Guardrails",42,18,"#5ee6c4"],["Vector Embedding Match",118,43,"#35d9ff"],["LLM Completion Stream",280,82,"#8b7cff"]].map(([label,ms,width,color])=><div key={label as string}><div className="mb-2 flex justify-between font-mono text-[10px]"><span className="text-slate-400">{label}</span><span style={{color:color as string}}>{resetting?0:ms}ms</span></div><div className="h-2 overflow-hidden rounded border border-cyan-400/15 bg-black"><motion.div animate={{width:resetting?0:`${width}%`}} transition={spring} style={{backgroundColor:color as string}} className="h-full opacity-80"/></div></div>)}</div></article>
  <article className="glass-card min-h-[330px] p-6"><div className="flex justify-between font-mono text-[9px]"><span className="text-cyan-300">NODE_04 / SUMMARY</span><span className="text-slate-600">DEMO DATA</span></div><div className="mt-7 grid gap-5">{[["TOTAL_REQUESTS_MANAGED","142,830","text-cyan-300"],["CONTEXT_PRECISION_RATIO","99.4%","text-[#5ee6c4]"],["COMPUTE_EFFICIENCY_INDEX","87.2","text-violet-300"]].map(([label,value,color])=><div key={label}><p className="font-mono text-[9px] text-slate-600">{label}</p><motion.b animate={{opacity:resetting?.2:1}} className={`mt-1 block text-3xl tabular-nums ${color}`}>{resetting?"0":value}</motion.b></div>)}</div><button onClick={flush} disabled={resetting} className="mt-7 flex items-center gap-2 rounded-lg border border-violet-400/20 px-3 py-2 font-mono text-[9px] text-violet-200"><RotateCcw className={`h-3 w-3 ${resetting?"animate-spin":""}`}/>FLUSH PIPELINE</button></article>
 </div></div></section>
}
