"use client";
import { useEffect,useRef } from "react";

export function NeuralBackground(){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;let cancelled=false,dispose=()=>{};(async()=>{const THREE=await import("three");if(cancelled)return;const compact=innerWidth<760,reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;let effectsOff=localStorage.getItem("gopal-reduced-effects")==="true",frame=0,last=performance.now(),scrollTarget=0;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,100);camera.position.z=12;
 const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:false,powerPreference:"high-performance"});renderer.setClearColor(0xf8fafc,1);renderer.setPixelRatio(Math.min(devicePixelRatio,1));renderer.setSize(innerWidth,innerHeight,false);
 const group=new THREE.Group();scene.add(group);const count=compact?520:1500,positions=new Float32Array(count*3),colors=new Float32Array(count*3),centers=[[-3,-1,0],[2.8,-1,-1],[-1,2,-2],[3,2,1],[0,0,2]],cyan=new THREE.Color(0x059669),violet=new THREE.Color(0x2563eb);
 // A lightweight three-layer agent core: orchestrator, tool calling and vector memory.
 const core=new THREE.Group();scene.add(core);core.position.set(compact?2.4:3.9,.4,-1.2);
 const layerMaterial=(color:number,opacity:number)=>new THREE.MeshBasicMaterial({color,transparent:true,opacity,wireframe:true,depthWrite:false});
 const layers=[
  new THREE.Mesh(new THREE.IcosahedronGeometry(.78,1),layerMaterial(0x2563eb,.34)),
  new THREE.Mesh(new THREE.TorusGeometry(1.18,.055,10,64),layerMaterial(0x059669,.42)),
  new THREE.Mesh(new THREE.TorusKnotGeometry(.82,.035,72,8,2,3),layerMaterial(0x2563eb,.28))
 ];
 layers[1].rotation.x=Math.PI/2.5;layers[2].rotation.x=Math.PI/4;layers.forEach(layer=>core.add(layer));
 for(let i=0;i<count;i++){const c=centers[i%5],r=Math.pow(Math.random(),.55)*2.7,a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1),color=i%3?cyan:violet;positions[i*3]=c[0]+r*Math.sin(b)*Math.cos(a);positions[i*3+1]=c[1]+r*Math.cos(b);positions[i*3+2]=c[2]+r*Math.sin(b)*Math.sin(a);colors.set([color.r,color.g,color.b],i*3)}
 const pg=new THREE.BufferGeometry();pg.setAttribute("position",new THREE.BufferAttribute(positions,3));pg.setAttribute("color",new THREE.BufferAttribute(colors,3));const pm=new THREE.PointsMaterial({size:.026,vertexColors:true,transparent:true,opacity:.42,depthWrite:false,blending:THREE.AdditiveBlending});group.add(new THREE.Points(pg,pm));
 const lineData:number[]=[];let links=0,limit=compact?500:1800;for(let i=0;i<count&&links<limit;i+=3)for(let o=5;o<50&&links<limit;o+=5){const j=(i+o)%count,dx=positions[i*3]-positions[j*3],dy=positions[i*3+1]-positions[j*3+1],dz=positions[i*3+2]-positions[j*3+2];if(dx*dx+dy*dy+dz*dz<2){lineData.push(positions[i*3],positions[i*3+1],positions[i*3+2],positions[j*3],positions[j*3+1],positions[j*3+2]);links++}}
 const lg=new THREE.BufferGeometry();lg.setAttribute("position",new THREE.Float32BufferAttribute(lineData,3));const lm=new THREE.LineBasicMaterial({color:0x2563eb,transparent:true,opacity:.1,depthWrite:false});group.add(new THREE.LineSegments(lg,lm));
 const pointer={x:0,y:0},target={x:0,y:0};const move=(e:PointerEvent)=>{target.x=(e.clientX/innerWidth-.5)*2;target.y=(e.clientY/innerHeight-.5)*2},scroll=()=>scrollTarget=Math.min(scrollY/innerHeight,4),resize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)};
 const render=(now:number)=>{if(effectsOff)return;const dt=Math.min((now-last)/1000,.04);last=now;pointer.x+=(target.x-pointer.x)*.04;pointer.y+=(target.y-pointer.y)*.04;if(!reduced){group.rotation.y+=dt*.035;group.rotation.x+=dt*.01;core.rotation.y+=dt*.18;core.rotation.x+=dt*.055}const progress=Math.min(scrollTarget/3,1);layers[0].position.y+=(progress*2.25-layers[0].position.y)*.04;layers[0].position.x+=(-progress*.85-layers[0].position.x)*.04;layers[1].position.x+=(progress*1.65-layers[1].position.x)*.04;layers[1].position.y+=(-progress*.35-layers[1].position.y)*.04;layers[2].position.x+=(-progress*1.55-layers[2].position.x)*.04;layers[2].position.y+=(-progress*1.55-layers[2].position.y)*.04;core.scale.setScalar(1-progress*.18);camera.position.x+=(pointer.x*.4-camera.position.x)*.03;camera.position.y+=(-pointer.y*.3-camera.position.y)*.03;camera.position.z+=(12-scrollTarget*.65-camera.position.z)*.03;camera.lookAt(0,0,0);renderer.render(scene,camera);if(!reduced&&!document.hidden)frame=requestAnimationFrame(render)};
 const visibility=()=>{cancelAnimationFrame(frame);if(!document.hidden&&!reduced&&!effectsOff){last=performance.now();frame=requestAnimationFrame(render)}},effects=(e:Event)=>{effectsOff=(e as CustomEvent).detail.reduced;cancelAnimationFrame(frame);if(!effectsOff){last=performance.now();frame=requestAnimationFrame(render)}};
 addEventListener("pointermove",move,{passive:true});addEventListener("scroll",scroll,{passive:true});addEventListener("resize",resize,{passive:true});addEventListener("gopal-effects",effects);document.addEventListener("visibilitychange",visibility);scroll();if(!effectsOff)frame=requestAnimationFrame(render);
 dispose=()=>{cancelAnimationFrame(frame);removeEventListener("pointermove",move);removeEventListener("scroll",scroll);removeEventListener("resize",resize);removeEventListener("gopal-effects",effects);document.removeEventListener("visibilitychange",visibility);pg.dispose();pm.dispose();lg.dispose();lm.dispose();layers.forEach(layer=>{layer.geometry.dispose();layer.material.dispose()});renderer.dispose()};})();return()=>{cancelled=true;dispose()};
 },[]);return <canvas id="webgl-canvas" ref={ref} className="pointer-events-none fixed inset-0 z-0 h-screen w-screen bg-[#F8FAFC]" aria-hidden="true"/>
}
