"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Activity, ArrowUpRight, CheckCircle2, Code2, ExternalLink, GitBranch, Mail, Play, UserRound } from "lucide-react";
import { FormEvent, ReactNode, useState } from "react";
import { certifications, projects, skills } from "../lib/data";

const spring = { type: "spring" as const, stiffness: 200, damping: 25 };
const Github = Code2;
const Linkedin = UserRound;
type Project = typeof projects[number];

function Section({id,eyebrow,title,description,children}:{id:string;eyebrow:string;title:string;description?:string;children:ReactNode}) {
  return <section id={id} className="relative z-10 scroll-mt-20 border-t border-white/[.07] px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-7xl"><motion.header initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.3}} transition={spring} className="mb-12 grid gap-5 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><p className="mb-3 font-mono text-[10px] uppercase tracking-[.22em] text-blue-400">{eyebrow}</p><h2 className="max-w-4xl text-4xl font-bold tracking-[-.045em] sm:text-6xl">{title}</h2></div>{description && <p className="max-w-xl leading-7 text-slate-400 lg:justify-self-end">{description}</p>}</motion.header>{children}</div></section>;
}

function About(){return <Section id="about" eyebrow="01 / PROFILE" title="Domain depth meets agentic engineering." description="Seven years across construction operations and data science inform a workflow-first approach to AI."><div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><div className="glass-card p-7 sm:p-10"><p className="text-xl leading-9 text-slate-300">I focus on prompt engineering, advanced RAG topologies, autonomous multi-agent workflows, and the evaluation systems required to make them reliable.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{[["7+","Years domain experience"],["9","Blueprint systems"],["22","Credentials retained"]].map(([n,l])=><div key={l} className="rounded-2xl border border-white/[.07] bg-black/20 p-5"><b className="text-3xl">{n}</b><p className="mt-2 text-xs text-slate-500">{l}</p></div>)}</div></div><div className="glass-card p-7"><p className="font-mono text-[10px] text-emerald-300">CURRENT_EXECUTION_CONTEXT</p>{["Evaluation-led RAG","Stateful agent orchestration","Low-latency model serving"].map(x=><motion.div key={x} whileHover={{x:6}} transition={spring} className="flex items-center gap-3 border-b border-white/[.07] py-5"><CheckCircle2 className="h-4 w-4 text-emerald-400" />{x}</motion.div>)}</div></div></Section>}

function ProjectCard({project,index}:{project:Project;index:number}){const [tab,setTab]=useState<"overview"|"architecture">("overview");return <motion.article layout whileHover={{y:-6}} transition={spring} className="glass-card group flex min-h-[430px] flex-col overflow-hidden"><div className="h-px bg-gradient-to-r from-blue-400 via-violet-500 to-emerald-400"/><div className="flex flex-1 flex-col p-6"><div className="flex justify-between font-mono text-[9px] text-slate-500"><span>RUN-ID: #{project.id.toUpperCase()}</span><span>0{index+1}</span></div><h3 className="mt-5 text-xl font-semibold">{project.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{project.impact}</p><div className="mt-6 flex rounded-xl border border-white/[.07] bg-black/20 p-1">{(["overview","architecture"] as const).map(t=><button key={t} onClick={()=>setTab(t)} className="relative flex-1 rounded-lg px-3 py-2 font-mono text-[10px] uppercase text-slate-400">{tab===t&&<motion.span layoutId={`tab-${project.id}`} transition={spring} className="absolute inset-0 rounded-lg bg-white/[.08]"/>}<span className="relative">{t}</span></button>)}</div><AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={spring} className="mt-5 min-h-28">{tab==="overview"?<p className="text-sm leading-6 text-slate-400">{project.goal}</p>:<div className="flex flex-wrap items-center gap-2">{project.flow.split(" → ").map((node,i)=><span key={node} className="contents"><span className="rounded-lg border border-blue-400/15 bg-blue-400/[.05] px-2.5 py-2 font-mono text-[9px] text-blue-200">{node}</span>{i<project.flow.split(" → ").length-1&&<span className="text-slate-700">→</span>}</span>)}</div>}</motion.div></AnimatePresence><div className="mt-auto flex flex-wrap gap-2">{project.stack.map(x=><span key={x} className="rounded-md bg-white/[.05] px-2 py-1 font-mono text-[9px] text-slate-400">{x}</span>)}</div><div className="mt-6 flex gap-4 border-t border-white/[.07] pt-5 text-xs"><a href="https://github.com/gopalgk53/construction-legal-ai-suite" target="_blank" rel="noreferrer" className="flex items-center gap-1 text-blue-300">Inspect code <Code2 className="h-3 w-3"/></a><a href="#playground" className="flex items-center gap-1 text-slate-400">Live simulator <Play className="h-3 w-3"/></a></div></div></motion.article>}

function Projects(){return <Section id="projects" eyebrow="02 / CASE STUDIES" title="Architecture-first AI systems." description="Nine blueprint projects with explicit goals, implementation stacks, and system flows. Metrics shown are project targets—not unverified production claims."><div className="mb-6 flex flex-wrap gap-2"><span className="metric">TTFT target: &lt;150ms</span><span className="metric">Orchestration: LangGraph</span><span className="metric">Vector stores: Qdrant / FAISS</span></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{projects.map((p,i)=><ProjectCard key={p.id} project={p} index={i}/>)}</div></Section>}

function Skills(){return <Section id="skills" eyebrow="03 / LATENT SKILL MAP" title="The execution stack."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{skills.map((s,i)=><motion.div key={s.group} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{...spring,delay:i*.03}} className="glass-card p-6"><div className="flex items-center justify-between"><h3 className="font-semibold">{s.group}</h3><Activity className="h-4 w-4 text-violet-400"/></div><div className="mt-6 flex flex-wrap gap-2">{s.items.map(x=><motion.span key={x} whileHover={{y:-2,scale:1.03}} transition={spring} className="rounded-full border border-white/[.08] px-3 py-2 font-mono text-[10px] text-slate-400">{x}</motion.span>)}</div></motion.div>)}</div></Section>}

function Playground(){const [value,setValue]=useState(62);return <Section id="playground" eyebrow="04 / LIVE SIMULATOR" title="Inspect a retrieval decision." description="A local, deterministic UI simulation—no data leaves your browser."><div className="glass-card grid gap-7 p-7 lg:grid-cols-[.7fr_1.3fr]"><div><label className="font-mono text-xs text-slate-400">SIMILARITY_THRESHOLD: {(value/100).toFixed(2)}</label><input aria-label="Similarity threshold" type="range" min="35" max="90" value={value} onChange={e=>setValue(Number(e.target.value))} className="mt-5 w-full accent-violet-500"/><p className="mt-5 text-sm leading-6 text-slate-500">Raise the threshold to trade recall for stricter semantic matching.</p></div><div className="space-y-3">{[[.87,"Payment clauses and lien deadlines"],[.71,"State-specific preliminary notice rules"],[.54,"General contract administration"]].map(([score,label])=><motion.div key={label as string} animate={{opacity:Number(score)>=value/100?1:.2,x:Number(score)>=value/100?0:8}} transition={spring} className="flex items-center justify-between rounded-xl border border-white/[.07] bg-black/20 p-4"><span className="text-sm">{label}</span><span className="font-mono text-xs text-emerald-300">{score}</span></motion.div>)}</div></div></Section>}

function Experience(){return <Section id="experience" eyebrow="05 / TRACE" title="Experience as an execution log."><div className="glass-card p-7 font-mono"><p className="text-[10px] text-violet-400">trace_id: exp_2019_2026</p>{[["HEAD","Generative AI systems","RAG · agents · evaluation · LLMOps"],["main~1","Data science","Predictive ML · explainability · document intelligence"],["main~2","Construction research & operations","Domain workflows · compliance · business analysis"]].map(([hash,title,copy],i)=><div key={hash} className="grid gap-3 border-l border-blue-400/20 py-6 pl-6 sm:grid-cols-[100px_1fr]"><span className="text-xs text-emerald-300"><GitBranch className="mr-2 inline h-3 w-3"/>{hash}</span><div><h3 className="font-sans font-semibold">{title}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{copy}</p></div></div>)}</div></Section>}

function Certifications(){const [all,setAll]=useState(false);const visible=all?certifications:certifications.slice(0,6);return <Section id="certifications" eyebrow="06 / VERIFIED LEARNING" title="Credentials, preserved."><div className="grid gap-3 md:grid-cols-2">{visible.map(([name,meta,url])=><motion.a key={name} href={url} target="_blank" rel="noreferrer" whileHover={{x:5}} transition={spring} className="glass-card flex items-center justify-between p-5"><div><h3 className="text-sm font-medium">{name}</h3><p className="mt-1 text-xs text-slate-500">{meta}</p></div><ExternalLink className="h-4 w-4 text-blue-400"/></motion.a>)}</div><motion.button onClick={()=>setAll(!all)} whileTap={{scale:.97}} transition={spring} className="mt-7 rounded-full border border-white/15 px-5 py-3 text-sm">{all?"Show featured":`View all ${certifications.length} credentials`}</motion.button></Section>}

function Contact(){const [status,setStatus]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),name=String(d.get("name")||""),email=String(d.get("email")||""),message=String(d.get("message")||"");if(!name.trim()||!/^\S+@\S+\.\S+$/.test(email)||message.trim().length<10){setStatus("Check name, email, and message (10+ characters).");return}setStatus("Opening your email client…");const subject=encodeURIComponent(`Portfolio inquiry from ${name}`);const body=encodeURIComponent(`${message}\n\nFrom: ${email}`);location.href=`mailto:gopalgk53@yahoo.com?subject=${subject}&body=${body}`;}
return <Section id="contact" eyebrow="07 / CONNECT" title="Ready to deploy next-gen AI?"><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="glass-card p-7"><p className="font-mono text-[10px] text-emerald-300">SYSTEM_STATUS: ADAPTER_CONNECTED</p><div className="mt-7 space-y-2">{[["GitHub","https://github.com/gopalgk53",Github],["LinkedIn","https://www.linkedin.com/in/maddipalli-gopalakrishna-b3598718b",Linkedin],["Email","mailto:gopalgk53@yahoo.com",Mail]].map(([label,url,Icon])=><a key={label as string} href={url as string} target={String(url).startsWith("http")?"_blank":undefined} className="flex items-center justify-between border-b border-white/[.07] py-4 text-sm text-slate-400"><span className="flex items-center gap-2">{<Icon className="h-4 w-4"/>}{label as string}</span><ArrowUpRight className="h-4 w-4"/></a>)}</div><a href="/Gopalakrishna_Maddipalli_CV.pdf" className="mt-5 inline-flex text-sm text-blue-300">Download Resume ↗</a></div><form onSubmit={submit} className="glass-card p-7"><p className="mb-6 font-mono text-xs text-slate-400">System: “Awaiting incoming transmission parameters.”</p><div className="grid gap-4 sm:grid-cols-2"><input name="name" aria-label="Name" placeholder="[User Name]" className="field"/><input name="email" type="email" aria-label="Email" placeholder="[User Email]" className="field"/></div><textarea name="message" aria-label="Message" placeholder="[Message Body]" rows={5} className="field mt-4 resize-none"/><div className="mt-5 flex flex-wrap items-center gap-4"><motion.button whileHover={{y:-3}} whileTap={{scale:.97}} transition={spring} className="rounded-full bg-gradient-to-r from-blue-500 to-violet-500 px-5 py-3 text-sm font-semibold">Execute transmission</motion.button><span role="status" className="text-xs text-slate-500">{status}</span></div></form></div></Section>}

export function Portfolio(){return <><About/><Projects/><Skills/><Playground/><Experience/><Certifications/><Contact/><footer className="relative z-10 border-t border-white/[.07] px-5 py-10"><pre className="mx-auto max-w-xl overflow-auto rounded-2xl border border-white/[.08] bg-black/30 p-5 text-xs leading-6 text-slate-500">{JSON.stringify({status:200,developer:"Gopalakrishnan",domain:"gopalakrishnagenai.in",location:"India",available_for:"GenAI Engineering & AI Architecture"},null,2)}</pre></footer></>}
